### ISSUE TITLE
There's someone here?

### ISSUE THREAD

**Issue by ghost** [rosefromthedead/csgo-gsi#2]
I forked your library, fixed bugs and made a new example. But I didn't look at the license and github banned me. This license is a real pain in the ass. So... the question is are you alive? Can I somehow change the code in the repository?

**Comment by rosefromthedead** [comment]
The code isn't mine, check the committer on the license. I'm alive thanks. If you want a library like this I'd recommend writing it from scratch without using boringcactus' code, because they seem to have used this crazy license for everything. Plus serde's model cannot handle one of Valve's file formats, so the serde library they used for this has been broken forever. If you do write a new library feel free to ping me to get your first user :P

I'm not sure whether I'm at risk for hosting the code here, but uhh.. I sure hope not? We'll see.

**Comment by ghost** [comment]
OK. Thank you very much for answering. Maybe I'll try to create my own library.
